.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WAV2RTP 1 "June 29, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wav2rtp \- program  to generate RTP data packets and save it  into pcap or wav file, also can emulate network delays and losses.
.SH SYNOPSIS
.B wav2rtp
.RI [-f|--from-file] "  file.wav  "  [-t|--to-file] "  file.pcap "  [-c|--codec] "  codec "  [ " other   options " ... "  ]
.SH DESCRIPTION
This manual page documents briefly the
.B wav2rtp
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBwav2rtp\fP is a simple tool intended to convert speech data from wav files to
RTP data stream. Currently it supports conversion data with codec G.711u, GSM
06.10 FR and Speex and may write RTP stream to pcap file. With this tool you can
also emulate random losses and delays which may have a place in the real network
communication.

The main purpose of this tool is to be used along with SIPp testing utility.

This tool was created and currently developed as part of the research project
which explore an influence of different types of codecs and codec modes along
with different types of network losses and delays to speech quality. 

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP

.B \-h, \-\-help
Show summary of options.
.TP
.B \-f, \-\-from\-file
Filename from which sound (speech) data will be readed.
.TP
.B \-t, \-\-to\-file
Output pcap file
.TP
.B \-c, \-\-codec\-list
Comma separated list of codecs (without spaces), which will be used to encode .wav file.
.TP
.B \-o, \-\-output\-option
Output option which redefine /usr/local/etc/wav2rtp/output.conf. Recorded in form "section:key=value"
.TP
.B \-O, \-\-codecs\-option
Codec option which redefine /usr/local/etc/wav2rtp/codecs.conf. Recorded in the form "section:key=value"
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.

.SH EXAMPLES

.TP
.B wav2rtp -f test.wav -t test.pcap -c PCMU,GSM 
This reads file "test.wav" TWO TIMES, encodes it first with G.711 then with
GSM 06.10 and stores data in pcap file "test.pcap"
.TP
.B wav2rtp -f test.wav -t test.pcap -c PCMU,GSM -o log:enabled=true
This case is the same as previous plus logging to stdout will be available


.SH BUGS

The one strange feature of the wav2rtp is that this tool always produce pcap
file. Additionally you can request file in normal wav format. If you just want
to get only wav file, use these option combination: 

.B -t /dev/null -o wavfile_output:filename=output.wav


.SH SEE ALSO
.BR codec.conf (1),
.BR output.conf (1).
.br
.SH AUTHOR
wav2rtp was written by Roman Imankulov <imankuloff@users.sourceforge.net>.
.PP
